Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/password_manager/initial-registration/

Django Version: 4.1.7
Python Version: 3.9.21
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'password_manager']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/middleware.py", line 59, in process_response
    request.session.save()
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 80, in save
    return self.create()
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 82, in save
    obj = self.create_model_instance(data)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 69, in create_model_instance
    session_data=self.encode(data),
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 94, in encode
    return signing.dumps(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/signing.py", line 150, in dumps
    return TimestampSigner(key, salt=salt).sign_object(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/signing.py", line 228, in sign_object
    data = serializer().dumps(obj)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/signing.py", line 125, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
  File "/usr/local/Cellar/python@3.9/3.9.21/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.9/3.9.21/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.21/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.21/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /password_manager/initial-registration/
Exception Value: Object of type TOTPDevice is not JSON serializable
