Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/password_manager/initial-registration/

Django Version: 4.1.7
Python Version: 3.9.21
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'password_manager']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/amody/Documents/GitHub/security_tools_copy/password_manager/views.py", line 86, in initial_registration
    user.save()
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1659, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1583, in as_sql
    value_rows = [
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1584, in <listcomp>
    [
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1585, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1523, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 925, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/amody/.pyenv/versions/crypt/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2598, in get_db_prep_value
    return connection.Database.Binary(value)

Exception Type: TypeError at /password_manager/initial-registration/
Exception Value: memoryview: a bytes-like object is required, not 'str'
